// Programmer:  Devin Wood
// MST Username: dwwdtv
// Instructor:  Ayan
// Section:     301
// Date:        09/15/2020
// File:        primefactorsumofdigits.cpp
// Description: This program gives the user two choices using a switch-case statement.
// 		the first case prompts the user to input a number, and then a while
// 		loop finds all of the prime factors of that number and prints them
// 		to the terminal. The second case generates a random number, and then
// 		finds the sum of the digits of the random number and prints the sum
// 		to the terminal.

#include <iostream>
#include <math.h>
#include <stdlib.h>
#include <time.h>

using namespace std;


int main()
{
  srand(time(NULL));

  short choice;
  int n;
  int sum = 0;
  int random_number = rand();
  int number;

  // Prompts user to choose which switch-case statement to execute

  cout << "Enter the choice (1-2):" << endl << endl;
  cout << "1: Prime factors of number input by user" << endl;
  cout << "2: Sum of the digits of a random number generated by rand()" << endl << endl;

  cout << "Your choice?  ";
  cin >> choice;
  
  // switch-case statements are defined in this block of code by description of the program

  switch (choice)
  {
    case 1:
        cout << "Enter a number:  ";
	cin >> n;

	cout << "The prime factors of " << n << " are: ";

	if (n % 2 == 0)
	{
	  cout << 2 << " ";
	}


        while (n % 2 == 0)
        {
          n = n / 2;
        }

        for (int i = 3; i <= sqrt(n); i += 2)
        {
          while (n % i == 0)
          {
            cout << i << " ";
            n = n / i;
          }
        }

        if (n > 2)
        {
          cout << n;
        }

	cout << "" << endl;
        break;

    case 2:
        cout << "The random number generated is: " << random_number << endl;        
	number = random_number;

	while (number != 0)
	{
	  sum = sum + (number % 10);
	  number /= 10;
	}

	cout << "The sum of the random number (" << random_number << ") is: " << sum << endl;
        break;

// default case will execute if the choice entered by the user is not 1 or 2	
    default:
	cout << "Wrong choice entered." << endl; 
	break;
  }

  return 0;
}
